/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CountTo: typeof import('./../src/components/count-to.vue')['default']
    LineAndBar: typeof import('./../src/components/echarts/LineAndBar.vue')['default']
    LineChart: typeof import('./../src/components/echarts/LineChart.vue')['default']
    Loading: typeof import('./../src/components/loading/Loading.vue')['default']
    NaiveProvider: typeof import('./../src/components/naive-provider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NThemeEditor: typeof import('naive-ui')['NThemeEditor']
    PerformanceMonitor: typeof import('./../src/components/performance-monitor.vue')['default']
    Permission: typeof import('./../src/components/permission.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./../src/components/Toast/Toast.vue')['default']
    Ts: typeof import('./../src/components/ts.vue')['default']
  }
}
